language: "ko-KR" # 한국말로 설정

# Set the tone of reviews and chat. Example: 'You must use talk like Mr. T. I pity the fool who doesn't!'
# Default: ""
tone_instructions: ""

reviews:
  profile: "assertive"
  request_changes_workflow: true
  high_level_summary: true
  collapse_walkthrough: false
  review_status: true
  auto_review:
    enabled: true
    drafts: false
  poem: false
  tools:
    gitleaks:
      enabled: true
    detekt:
      enabled: true
    yamllint:
      enabled: true

chat:
  auto_reply: true

knowledge_base:
  code_guidelines:
    enabled: true
